- name: Arch Linux installation
  hosts: localhost
  become: yes
  roles:
    - { role: base-packages, tags: ['base', 'config'] }
    - { role: xorg, tags: ['xorg', 'config'] }
    - { role: sound, tags: ['sound', 'config'] }
    - { role: bspwm, tags: ['bspwm', 'config'] }
    - { role: sxhkd, tags: ['sxhkd', 'config'] }
    - { role: picom, tags: ['picom', 'config'] }
    - { role: kitty, tags: ['kitty', 'config'] }
    - { role: shell, tags: ['shell', 'config'] }
    - { role: fonts, tags: ['fonts', 'config'] }
    - { role: polybar, tags: ['polybar', 'config'] }
    - { role: rofi, tags: ['rofi', 'config'] }
    - { role: dunst, tags: ['dunst', 'config'] }
    - { role: flameshot, tags: ['flameshot', 'config'] }
    - { role: openvpn, tags: ['openvpn', 'config'] }
    - { role: nvim, tags: ['nvim', 'config'] }
    - { role: virtualization, tags: ['virt', 'config'] }

