- name: Arch Linux installation
  hosts: localhost
  become: yes
  roles:
    - { role: aur, tags: ['aur'] }
    - { role: sway, tags: ['sway'] }
    - { role: waybar, tags: ['waybar'] }
    - { role: sound, tags: ['sound'] }
    - { role: desktop-apps, tags: ['desktop-apps'] }
    - { role: cli-apps, tags: ['cli-apps'] }
    - { role: sddm, tags: ['sddm' ] }
    - { role: shell, tags: ['shell'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: openvpn, tags: ['openvpn'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: virtualization, tags: ['virt'] }

