- name: Setup Arch Linux on Thinkpad
  hosts: localhost
  become: yes
  roles:
    - { role: network, tags: ['network'] }
    - { role: aur, tags: ['aur'] }
    - { role: xorg, tags: ['xorg'] }
    - { role: bspwm, tags: ['bspwm'] }
    - { role: sxhkd, tags: ['sxhkd']}
    - { role: sound, tags: ['sound'] }
    - { role: desktop-apps, tags: ['desktop-apps'] }
    - { role: cli-apps, tags: ['cli-apps'] }
    - { role: sddm, tags: ['sddm' ] }
    - { role: shell, tags: ['shell'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: virtualization, tags: ['virt'] }

