- name: Install bspwm
  pacman:
    name: bspwm
    state: present
    update_cache: yes

- name: Create config dir
  file:
    path: '/home/{{ user }}/.config/bspwm/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Create config file
  copy:
    src: bspwmrc
    dest: '/home/{{ user }}/.config/bspwm/'
    mode: 0644
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Copy wallpaper
  copy:
    src: wallpaper.png
    dest: '/home/{{ user}}/.config/bspwm/'
    mode: 0644
    owner: '{{ user }}'
    group: '{{ user }}'
