- name: Ensure pacman repos are synchronized
  pacman:
    update_cache: yes

- name: Install CLI apps
  pacman:
    name:
      - aws-cli
      - curl
      - dnsutils
      - exa
      - git
      - htop
      - inetutils
      - ipcalc
      - nmap
      - openssh
      - python3
      - python-pip
      - rsync
      - unzip
      - wget
      - xclip
      - xterm
      - zip
    state: present
