- name: Create aur_builder user
  user:
    name: aur_builder
    create_home: no
    group: wheel

- name: Configure sudo for aur_builder
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Install paru using makepkg
  aur:
    name: paru
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder
