- name: Install sxhkd
  pacman:
    name: sxhkd
    state: latest
    update_cache: yes

- name: Create config dir
  file:
    path: '/home/{{ user }}/.config/sxhkd/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Create config file
  copy:
    src: sxhkdrc
    dest: '/home/{{ user }}/.config/sxhkd/'
    mode: 0755
    owner: '{{ user }}'
    group: '{{ user }}'
